# -*- coding: utf-8 -*-
"""DAY_12_ST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_b_lEGFK9Iob7TbSbrXgOORwv07ccom
"""

def bfs(d,n):
    v=[]
    q=[n]
    while(q):
        for i in d[q[0]]:   #d[n] or d[q[0]]
            if(i not in q and i not in v):
                q.append(i)
        v.append(q.pop(0))
        print(v[-1],end=" ")

d={5:[7,3],7:[5,4,3],4:[7,8,2],8:[3,4,2],3:[5,7,8],2:[4,8]}
bfs(d,5)
print()
d={2:[1],1:[1,2,5],4:[5,1],5:[1,4,6],6:[5]}
bfs(d,2)

print('\n BFS')
def bfs(d,x):
    v=[]
    q=[x]
    while q:
        for i in d[q[0]]:
            if (i not in q and i not in v):
                q.append(i)
        v.append(q.pop(0))
        print(v[-1],end=' ')
d={5:[7,3],7:[5,4,3],4:[7,8,2],8:[3,4,2],3:[5,7,8],2:[4,8]}
bfs(d,5)
print()
d={5:[7,3],7:[5,4,3],4:[7,8,2],8:[3,4,2],3:[5,7,8],2:[4,8]}
bfs(d,5)

def fun(d,x,e,c,m,l1):
    l.append(x)
    if(x==e):
        if(c<m):
            m=c
            l1=l.copy()
        l.pop()
        return m,l1
    for i in d[x]:

            m,l1=fun(d,i[0],e,c+i[1],m,l1)
    l.pop()
    return m,l1
d={(0,1,2),(0,4,2),(1,0,2),(1,2,3),(1,4,2),4:[(2,1,6),(2,3,1),(2,5,1)],
   8:[(3,3),(4,1),(2,1)],3:[(5,1),(7,2),(8,3)],2:[(4,2),(8,1)]}
l=[]
print(fun(d,5,2,0,99999,[]))
5:0
7:1
4:2
8:3
3:4
2:5

def fun(l1,l2,l3):
    for i in l1:
        if i%2==0:
            l3.append(i)
    for j in l2:
        if j%2!=0:
            l3.append(fun(i+j))
    fun(l1,l3)
l1=[6,3,2,9,4,7]
l2=[8,7,5,3,6,9]
l3=[]
fun(l1,l3)

def fun(l1,l2,l3):
    for i in l1:
        for j in l2:
            if i%2==0 and j%2!=0:
                l3.append(i+j)
    return l3
l1=[6,3,2,9,4,7]
l2=[8,7,5,3,6,9]
l3=[]
print(fun(l1,l2,l3))

def fun(l1,l2,l3):
  s=0
  for i in l1:
      for j in l2:
        if i%2==0 and j%2!=0:
              l3.append(i)
              l3.append(j)
              s=i+j
              l3.append(s)
  return l3
l1=[6,3,2,9,4,7]
l2=[8,7,5,3,6,9]
l3=[]
print(fun(l1,l2,l3))

